services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
          target: /app/package.json
