# Docker compose 
# ______________

# services:
#   web:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     working_dir: /app
#     volumes:
#       - .:/app
#     ports:
#       - 5173:5173
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     command: sh -c "npm install && npm run dev"


# Docker compose watch
# ____________________

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json