name: Check truthy falsy CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: Practice-CI

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: Practice-CI/package-lock.json
    - run: npm ci
    - run: npm test
