name: check-truthy-falsy values

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: Practice-CI
        
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup repo
          uses: actions/setup-node@v4
          with:
            node-version: '22.x'
            cache: 'npm'

        - name: Install dependencies
          uses: npm ci

        - name: Test
          uses: npm test